alter session set current_schema = MCREDIT;

ALTER TABLE MCREDIT.FW_POLICY_CONFIG_INFO
 ADD (DEPEND_CREDIT_AUTH_FLAG  NUMBER);

ALTER TABLE MCREDIT.FW_POLICY_CONFIG_INFO
 ADD (WITHDRAW_COST  NUMBER);


COMMENT ON COLUMN MCREDIT.FW_POLICY_CONFIG_INFO.DEPEND_CREDIT_AUTH_FLAG IS '依赖信用认证标示 1：需要 0：不需要';

COMMENT ON COLUMN MCREDIT.FW_POLICY_CONFIG_INFO.WITHDRAW_COST IS '提现费用';

CREATE TABLE MCREDIT.TB_TIMED_TASK_EXECUTE_INFO
(
  ID           NUMBER,
  CREATE_TIME  TIMESTAMP(6)                     NOT NULL,
  UPDATE_TIME  TIMESTAMP(6),
  TASK_ID      NUMBER,
  USE_TIME     NUMBER,
  RESULT       VARCHAR2(20 BYTE),
  REMARK       VARCHAR2(512 BYTE)
);

COMMENT ON TABLE MCREDIT.TB_TIMED_TASK_EXECUTE_INFO IS '任务执行情况';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_EXECUTE_INFO.ID IS 'ID';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_EXECUTE_INFO.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_EXECUTE_INFO.UPDATE_TIME IS '更新时间';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_EXECUTE_INFO.TASK_ID IS '任务ID';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_EXECUTE_INFO.USE_TIME IS '执行用时';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_EXECUTE_INFO.RESULT IS '执行结果';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_EXECUTE_INFO.REMARK IS '备注信息';


CREATE UNIQUE INDEX MCREDIT.FW_TIMED_TASK_EXECUTE_INFO_PK ON MCREDIT.TB_TIMED_TASK_EXECUTE_INFO(ID);

ALTER TABLE MCREDIT.TB_TIMED_TASK_EXECUTE_INFO ADD (
  CONSTRAINT FW_TIMED_TASK_EXECUTE_INFO_PK
 PRIMARY KEY
 (ID));
 
CREATE SEQUENCE MCREDIT.SEQ_TB_TIMED_TASK_EXECUTE_INFO;

CREATE TABLE MCREDIT.TB_TIMED_TASK_INFO
(
  ID                   NUMBER,
  TASK_TYPE            NUMBER,
  TASK_CONTENT         VARCHAR2(4000 CHAR),
  TASK_STATUS          NUMBER,
  EFFECTIVE_TIME       TIMESTAMP(6),
  RETRY_TIMES          NUMBER                   DEFAULT 0,
  EXECUTE_TIMES        NUMBER                   DEFAULT 0,
  LAST_EXECUTE_TIME    TIMESTAMP(6),
  CREATE_TIME          TIMESTAMP(6)             NOT NULL,
  UPDATE_TIME          TIMESTAMP(6),
  NOTIFY_EMAIL         VARCHAR2(4000 CHAR),
  NOTIFY_PHONE         VARCHAR2(4000 CHAR),
  LAST_EXECUTE_ID      NUMBER,
  RETRY_TIME_INTERVAL  NUMBER
);

COMMENT ON TABLE MCREDIT.TB_TIMED_TASK_INFO IS '定时任务信息表';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.ID IS '主键ＩＤ';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.TASK_TYPE IS '任务类型　1:sql,2:定制,3:rest';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.TASK_CONTENT IS '任务内容';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.TASK_STATUS IS '任务状态 1：待执行 2：执行中，3：待重试，4：执行失败，0：执行成功 ';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.EFFECTIVE_TIME IS '生效时间';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.RETRY_TIMES IS '重试次数';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.EXECUTE_TIMES IS '执行次数';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.LAST_EXECUTE_TIME IS '最后执行时间';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.UPDATE_TIME IS '更新时间';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.NOTIFY_EMAIL IS '通知的邮件';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.NOTIFY_PHONE IS '通知的手机';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.LAST_EXECUTE_ID IS '最后执行的ID';

COMMENT ON COLUMN MCREDIT.TB_TIMED_TASK_INFO.RETRY_TIME_INTERVAL IS '重试时间间隔（S）';


CREATE UNIQUE INDEX MCREDIT.FW_TIMED_TASK_INFO_PK ON MCREDIT.TB_TIMED_TASK_INFO
(ID);


ALTER TABLE MCREDIT.TB_TIMED_TASK_INFO ADD (
  CONSTRAINT FW_TIMED_TASK_INFO_PK
 PRIMARY KEY
 (ID));
 
CREATE SEQUENCE MCREDIT.SEQ_TB_TIMED_TASK_INFO;

GRANT DELETE, INSERT, SELECT, UPDATE ON MCREDIT.TB_TIMED_TASK_EXECUTE_INFO TO MCREDITUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON MCREDIT.TB_TIMED_TASK_INFO TO MCREDITUSER;
GRANT SELECT ON MCREDIT.SEQ_TB_TIMED_TASK_EXECUTE_INFO TO MCREDITUSER;
GRANT SELECT ON MCREDIT.SEQ_TB_TIMED_TASK_INFO TO MCREDITUSER;

ALTER SESSION SET CURRENT_SCHEMA = MCREDITUSER;
CREATE OR REPLACE SYNONYM MCREDITUSER.SEQ_TB_TIMED_TASK_EXECUTE_INFO FOR MCREDIT.SEQ_TB_TIMED_TASK_EXECUTE_INFO;

CREATE OR REPLACE SYNONYM MCREDITUSER.TB_TIMED_TASK_EXECUTE_INFO FOR MCREDIT.TB_TIMED_TASK_EXECUTE_INFO;

CREATE SYNONYM MCREDITUSER.TB_TIMED_TASK_INFO FOR MCREDIT.TB_TIMED_TASK_INFO;

CREATE SYNONYM MCREDITUSER.SEQ_TB_TIMED_TASK_INFO FOR MCREDIT.SEQ_TB_TIMED_TASK_INFO;

