alter session set current_schema = MCREDIT;
﻿
﻿insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'﻿2008',1,0,null,null,null,0,1,sysdate,'A',2,1,null);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'9999',1,0,null,null,null,0,1,sysdate,'mPOS',2,1,null);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2009',1,0,100000,0.0005,0.0005,0,1,sysdate,'树根',2,0,2);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2011',1,0,100000,0.0005,0.0005,0,1,sysdate,'树根',2,0,2);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2012',1,0,100000,0.0005,0.0005,0,1,sysdate,'树根',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2013',1,0,100000,0.0005,0.0005,0,1,sysdate,'树根',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2014',1,0,100000,0.0005,0.0005,0,1,sysdate,'树根',2,0,2);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2015',1,0,100000,0.0005,0.0005,0,1,sysdate,'树根',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2016',1,0,100000,0.0005,0.0005,0,1,sysdate,'树根',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2017',1,0,100000,0.0005,0.0005,0,1,sysdate,'树根',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2025',1,0,100000,0.0005,0.0005,0,1,sysdate,'树根',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2010',1,0,100000,0.0007,0.0007,0,1,sysdate,'全旗',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2019',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2020',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2021',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2022',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2023',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,2);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2024',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2026',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2123',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,2);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2124',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2125',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,2);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2126',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,2);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2127',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,2);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2128',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,2);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2129',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,2);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2130',1,0,100000,0,0,0,1,sysdate,'智奇盛（首刷）',2,0,2);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2027',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2028',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2029',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2030',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2031',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2032',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2033',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2034',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2094',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2095',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2096',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2097',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2098',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2099',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2100',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2101',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2102',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2103',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2104',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2106',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2107',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2108',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2109',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2110',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2112',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2113',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2114',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2115',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2116',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2117',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2118',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2119',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2120',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2121',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2122',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2405',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2035',1,0,100000,0,0,0,1,sysdate,'浪莎',2,0,3);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2039',1,0,100000,0,0,0,1,sysdate,'浪莎',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2089',1,0,100000,0,0,0,1,sysdate,'米刷',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2090',1,0,100000,0,0,0,1,sysdate,'米刷',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2091',1,0,100000,0,0,0,1,sysdate,'米刷',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2092',1,0,100000,0,0,0,1,sysdate,'米刷',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2093',1,0,100000,0,0,0,1,sysdate,'米刷',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2043',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2044',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2045',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2046',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2047',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2048',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2049',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2050',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2051',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2052',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2053',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2054',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2055',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2056',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2057',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2058',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2059',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2060',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2061',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2062',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2063',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2064',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2065',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2066',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2067',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2068',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2069',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2070',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2071',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2072',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2073',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2074',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2075',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2076',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2077',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2078',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2079',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2080',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2081',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2082',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2083',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2084',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2085',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2086',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2087',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2088',1,0,100000,0,0,0,1,sysdate,'醒融',2,0,0);

