ALTER SESSION SET CURRENT_SCHEMA = MCREDIT;
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2131',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2132',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2133',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2134',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2135',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2136',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2137',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2138',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2139',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2140',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2141',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2142',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2143',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2144',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2145',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2146',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2147',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2148',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);
insert into MCREDIT.FW_POLICY_CONFIG_INFO(ID,POLICY_ID,FAST_SETTLE_FLAG,AUTO_FAST_SETTLE_FLAG,FAST_SETTLE_LIMIT,HOLIDAY_RATIO,WORKDAY_RATIO,POMOTER_MODIFY_FLAG,STATUS,CREATE_TIME,POLICY_NAME,POLICY_TYPE,DEPEND_CREDIT_AUTH_FLAG,WITHDRAW_COST) 
 values(MCREDIT.SEQ_FW_POLICY_CONFIG_INFO.nextval,'2149',1,0,100000,0,0,0,1,sysdate,'付聪',2,0,0);

