ALTER SESSION SET CURRENT_SCHEMA = MCREDIT;

ALTER TABLE MCREDIT.FW_POLICY_CONFIG_INFO
 ADD (OA_TXN_WITHDRAW_COST  NUMBER);

COMMENT ON COLUMN MCREDIT.FW_POLICY_CONFIG_INFO.OA_TXN_WITHDRAW_COST IS '扫码交易提现费';

