var ALL_COND_ID=["shortPan","txnTimeStartStr","txnTimeEndStr","txnType","msh$txnType","stlDateStartStr","stlDateEndStr","txnNo","stlStatus","msh$stlStatus","amt","txnStatus","msh$txnStatus","cardType","msh$cardType","terminalNo","issuerId","msh$issuerId","csSettleFlag","merchantNo","merchantName","pmtMerchantNo","pmtMerchantName"];$ms.notInitMshIds=["msh$issuerId"];function myQuery(a){myAjaxQuery(a,contextPath+"/posMerchant/txn/queryTxn.do",ALL_COND_ID)}
function myDownload(){myAsyncDownload(contextPath+"/posMerchant/txn/downloadTxn.do",ALL_COND_ID)}
function checkBeforeQuery(){trimFields(["shortPan","txnNo","amt","terminalNo"]);if(elm("txnTimeStartStr").value==""&&elm("stlDateStartStr").value=="")return alert("\u8bf7\u9009\u62e9\u4ea4\u6613\u65f6\u95f4\u6216\u7ed3\u7b97\u65e5\u671f"),!1;if((elm("txnTimeStartStr").value!=""||elm("txnTimeEndStr").value!="")&&!timeInRange(elm("txnTimeStartStr").value,"yyyy-MM-dd HH:mm:ss",elm("txnTimeEndStr").value,"yyyy-MM-dd HH:mm:ss","90d"))return alert("\u4ea4\u6613\u65f6\u95f4\u8303\u56f4\u4e0d\u53ef\u8d85\u8fc790\u5929"),
!1;if((elm("stlDateStartStr").value!=""||elm("stlDateEndStr").value!="")&&!timeInRange(elm("stlDateStartStr").value,"yyyy-MM-dd HH:mm:ss",elm("stlDateEndStr").value,"yyyy-MM-dd HH:mm:ss","90d"))return alert("\u7ed3\u7b97\u65e5\u671f\u8303\u56f4\u4e0d\u53ef\u8d85\u8fc790\u5929"),!1;var a=validField(elm("txnNo"),18,"int");if(!a[0])return alert("\u53c2\u8003\u53f7"+a[1]),!1;a=validField(elm("amt"),15,"decimal");return!a[0]?(alert("\u4ea4\u6613\u91d1\u989d"+a[1]),!1):elm("issuerId").value==""&&elm("msh$issuerId").value!=
""?(alert("\u8bf7\u9009\u62e9\u6b63\u786e\u7684\u53d1\u5361\u673a\u6784"),!1):!0}var cardIssuerList=null;function forCardIssuerSelect(a){cardIssuerList==null?ajax(contextPath+"/common/dictionary/forCardIssuerSelect.do",{},function(c){cardIssuerList=eval(c);mselect(a,"issuerId",cardIssuerList,!1,220,150,1,1,null,!0,"cardIssuerMouseEvent");showOrHideOption("issuerId")}):(mselect(a,"issuerId",cardIssuerList,!1,220,150,1,1,null,!0,"cardIssuerMouseEvent"),showOrHideOption("issuerId"))}
function showOrHideOption(a){var c=elm("msh$"+a).value;if(a=elm(a+"_mselect"))if(a=a.getElementsByTagName("a"))for(var b,d=0;d<a.length;d++)b=a[d].innerHTML,a[d].parentNode.style.display=c==""||b.indexOf(c)!=-1?"":"none"}
function cardIssuerMouseEvent(a,c,b){optionsMouseEvent(a,c,b);a=mouseCoords(a);b=="over"?(b=c.innerHTML.replace("&nbsp;",""),elm("xstooltipDiv").innerHTML=b,xstooltip_resize("xstooltipDiv",b.length),xstooltip_show("xstooltipDiv",c.parentNode.parentNode,a.x,a.y)):xstooltip_hide("xstooltipDiv")}
function mouseCoords(a){a=a||window.event;return a.pageX||a.pageY?{x:a.pageX,y:a.pageY}:{x:a.clientX+(document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft),y:a.clientY+(document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop)}}function xstooltip_resize(a,c){var b=elm(a);b.style.width=c*12+"px";b.style.height="16px"}
function xstooltip_show(a,c,b,d){a=document.getElementById(a);a.style.top=d+5+"px";a.style.left=b+5+"px";a.style.display="block"}function xstooltip_hide(a){document.getElementById(a).style.display="none"}function changeEvent(a){clearVal(a);showOrHideOption(a)}function clearVal(a){elm(a).value=""}window.onload=function(){setTimeStartEnd(0,elm("txnTimeStartStr"),0,elm("txnTimeEndStr"));elm("issuerId").value="";elm("msh$issuerId").value=""};
