package com.sdp.mc.withdraw;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2012-08-07T17:44:50.380+08:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "PaymentFacade", 
                  wsdlLocation = "http://10.132.19.19:10001/?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class PaymentFacade extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "PaymentFacade");
    public final static QName NetTcpBindingIPaymentFacade = new QName("http://tempuri.org/", "NetTcpBinding_IPaymentFacade");
    public final static QName BasicHttpBindingIPaymentFacade = new QName("http://tempuri.org/", "BasicHttpBinding_IPaymentFacade");
    static {
        URL url = null;
        try {
            url = new URL("http://10.132.19.19:10001/?wsdl");
        } catch (MalformedURLException e) {
            LoggerFactory.getLogger(PaymentFacade.class.getName())
                .info(
                     "Can not initialize the default wsdl from {0}", "http://10.132.19.19:10001/?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PaymentFacade(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PaymentFacade(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentFacade() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /**
     *
     * @return
     *     returns IPaymentFacade
     */
    @WebEndpoint(name = "NetTcpBinding_IPaymentFacade")
    public IPaymentFacade getNetTcpBindingIPaymentFacade() {
        return super.getPort(NetTcpBindingIPaymentFacade, IPaymentFacade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPaymentFacade
     */
    @WebEndpoint(name = "NetTcpBinding_IPaymentFacade")
    public IPaymentFacade getNetTcpBindingIPaymentFacade(WebServiceFeature... features) {
        return super.getPort(NetTcpBindingIPaymentFacade, IPaymentFacade.class, features);
    }
    /**
     *
     * @return
     *     returns IPaymentFacade
     */
    @WebEndpoint(name = "BasicHttpBinding_IPaymentFacade")
    public IPaymentFacade getBasicHttpBindingIPaymentFacade() {
        return super.getPort(BasicHttpBindingIPaymentFacade, IPaymentFacade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPaymentFacade
     */
    @WebEndpoint(name = "BasicHttpBinding_IPaymentFacade")
    public IPaymentFacade getBasicHttpBindingIPaymentFacade(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIPaymentFacade, IPaymentFacade.class, features);
    }

}
