alter session set current_schema = MCREDIT;

ALTER TABLE MCREDIT.FW_WITHDRAW_REQ
 ADD (LAST_DETAIL_ID  NUMBER);

ALTER TABLE MCREDIT.FW_WITHDRAW_REQ
 ADD (HAS_OA_TXN  VARCHAR2(4 CHAR));

ALTER TABLE MCREDIT.FW_WITHDRAW_REQ
 ADD (REQ_EXTENTION  VARCHAR2(1024 CHAR));


COMMENT ON COLUMN MCREDIT.FW_WITHDRAW_REQ.LAST_DETAIL_ID IS '最后请求FOS的ID';

COMMENT ON COLUMN MCREDIT.FW_WITHDRAW_REQ.HAS_OA_TXN IS '是否包含扫码交易 1：是  0:否';

COMMENT ON COLUMN MCREDIT.FW_WITHDRAW_REQ.REQ_EXTENTION IS '请求扩展信息';

CREATE INDEX MCREDIT.IND_FW_WITHDRAW_REQ_LASTDEID ON MCREDIT.FW_WITHDRAW_REQ
(LAST_DETAIL_ID);