var contextPath=contextPath?contextPath:"/mc-intra-website",$p={ctrlAssVar:{showFlg:{},showElm:{}},loading:!1,loadingCap:null,twPage:null,ctrlFlag:null,pagingDivTop:0,mselect:{lastMselectId:null,mselectId:null,clkRcdElm:{}}};function elm(b){return document.getElementById(b)}function elms(b){return document.getElementsByName(b)}function showAndHide(b,c){for(var a=0;a<b.length;a++)elm(b[a]).style.display="";for(a=0;a<c.length;a++)elm(c[a]).style.display="none"}
function addEvent(b,c,a){(b.attachEvent||b.addEventListener)(b.attachEvent?"on"+c:c,a,!1)}function loading(b){if($p.loadingCap==null)$p.loadingCap=document.createElement("DIV"),$p.loadingCap.className="loadingCap",$p.loadingCap.innerHTML="\u6267\u884c\u4e2d...",document.body.appendChild($p.loadingCap);var c=getBodyScrollWidthHeight();$p.loadingCap.style.top=c.top+2+"px";$p.loadingCap.style.left=c.left+2+"px";$p.loading=b;$p.loadingCap.style.display=b?"":"none"}
function trim(b){return b.replace(/(^\s+)|(\s+$)/g,"")}function lrTrim(b){return b.replace(/(^\s*)|(\s*$)/g,"")}function trimFields(b){for(var c=0;c<b.length;c++){var a=elm(b[c]);if(a!=null&&a.value)a.value=trim(a.value)}}function getValue(b){b=typeof b=="string"?elm(b):b;if(b==null)return null;if(b.tagName=="INPUT"&&(b.type=="text"||b.type=="hidden")||b.tagName=="TEXTAREA")return b.value;else if(b.tagName=="SELECT")return b.selectedIndex==-1?null:b.options[b.selectedIndex].value}
function setValue(b,c){var a=typeof b=="string"?elm(b):b;if(a!=null)if(a.tagName=="SELECT")for(var d=0;d<a.options.length;d++){if(a.options[d].value==c){a.options[d].selected=!0;break}}else if(a.tagName=="INPUT"){if(a.type=="text"||a.type=="hidden")a.value=c}else if(a.tagName=="TEXTAREA")a.value=c}function lengthForByte(b){for(var c=0,a=0;a<b.length;a++)c+=/[\x00-\xff]/g.test(b.charAt(a))?1:2;return c}
function endsWith(b,c){for(var a=0;a<c.length;a++)if(b.length>c[a].length&&b.substring(b.length-c[a].length)==c[a])return!0;return!1}function forDecimal(b,c){if(""+b=="NaN")return"";var a=Math.pow(10,c),a=""+Math.round(parseFloat(b,10)*a)/a,d=a.indexOf(".");d!=-1&&a.length-d-1>c&&(a=a.substring(0,d+c+1));return parseFloat(a,10)}
function validField(b,c,a){b=b.value;if(/\&|\<|\>|\"|\'|\,/g.test(b))return[!1,"\u4e0d\u53ef\u542b\u6709\u7279\u6b8a\u5b57\u7b26"];var d=""+c,e=0,f=0;c!=null&&d.indexOf(",")!=-1?(e=parseInt(d.split(",")[0],10),f=parseInt(d.split(",")[1],10)):f=c;if(e>0&&b!=""&&lengthForByte(b)<e)return[!1,"\u957f\u5ea6\u4e0d\u53ef\u5c0f\u4e8e"+e+"\u4f4d"];if(f>0&&lengthForByte(b)>f)return[!1,"\u957f\u5ea6\u4e0d\u53ef\u8d85\u8fc7"+f+"\u4f4d"];if(a!=null){c=a.split(",");for(a=0;a<c.length;a++)if("blank"==c[a]){if(""==
trim(b))return[!1,"\u503c\u4e0d\u53ef\u4e3a\u7a7a"]}else if("email"==c[a]){if(""!=b&&!/^[-._A-Za-z0-9]+@([_A-Za-z0-9]+\.)+[A-Za-z0-9]{2,3}$/.test(b))return[!1,"\u90ae\u7bb1\u683c\u5f0f\u9519\u8bef"]}else if("int"==c[a]){if(""!=b&&!/^\d+$/.test(b))return[!1,"\u6570\u5b57\u683c\u5f0f\u9519\u8bef"]}else if("decimal"==c[a]){if(""!=b&&!/^((\d+\.?\d+)|(\d+))$/.test(b))return[!1,"\u6570\u5b57\u683c\u5f0f\u9519\u8bef"]}else if("time"==c[a]){if(""!=b&&!/(([0-1][0-9])|([2][0-3]))\:([0-5][0-9])\:([0-5][0-9])/g.test(b))return[!1,
"\u65f6\u95f4\u683c\u5f0f\u9519\u8bef"]}else if("phoneNo"==c[a]){if(""!=b&&!/^[0-9,\+,\-,\s]+$/.test(b))return[!1,"\u53f7\u7801\u683c\u5f0f\u9519\u8bef"]}else if("cardNo"==c[a]&&""!=b&&!/^[0-9]+[0-9,\-]*[0-9]+$/.test(b))return[!1,"\u8d26\u53f7\u683c\u5f0f\u9519\u8bef"]}return[!0,null]}function forParams(b){for(var c={},a=0;a<b.length;a++){var d=elm(b[a]);c[""+b[a]]=getValue(d)}return c}function getSubsOfMs(b,c){for(var a=0;a<b.length;a++)if(b[a].k==c||b[a].key==c)return b[a].s}
function getValueByKey(b,c){for(var a=0;a<b.length;a++)if(b[a].k==c||b[a].key==c)return b[a].v}function timeInRange(b,c,a,d,e){b==""&&(b="1970-01-01 00:00:00");if(a=="")var f=new Date,a=f.getFullYear(),a=a<1E3?1900+a:a,g=f.getMonth()+1,f=f.getDate()+1,a=a+"-"+(g<10?"0"+g:g)+"-"+(f<10?"0"+f:f)+" 00:00:00";c=parseDate(b,c);d=parseDate(a,d).getTime()-c.getTime();c=e.substring(0,e.length-1);e=e.substring(e.length-1);b=0;"d"==e?b=c*864E5:"H"==e?b=c*36E5:"m"==e?b=c*6E4:"s"==e&&(b=c*1E3);return d<=b}
function parseDate(b,c){var a=c.indexOf("yyyy"),d=c.indexOf("MM"),e=c.indexOf("dd"),a=b.substring(a,a+4),d=b.substring(d,d+2),e=b.substring(e,e+2),f=0,g=0,h=0;c.length>8&&(f=c.indexOf("HH"),g=c.indexOf("mm"),h=c.indexOf("ss"),f=b.substring(f,f+2),g=b.substring(g,g+2),h=b.substring(h,h+2));return new Date(a,d-1,e,f,g,h,0)}
function formatDate(b,c){var a=b.getFullYear(),d=b.getMonth()+1,e=b.getDate(),f=b.getHours(),g=b.getMinutes(),h=b.getSeconds();return c.replace("yyyy",a).replace("MM",d<10?"0"+d:d).replace("dd",e<10?"0"+e:e).replace("HH",f<10?"0"+f:f).replace("mm",g<10?"0"+g:g).replace("ss",h<10?"0"+h:h)}
function setTimeStartEnd(b,c,a,d){var e=new Date,f=e.getFullYear(),g=e.getMonth(),e=e.getDate();c.value=formatDate(new Date(f,g,e+b),"yyyy-MM-dd")+" 00:00:00";d.value=formatDate(new Date(f,g,e+a),"yyyy-MM-dd")+" 23:59:59"}function setDateStartEndRang(b,c,a,d){var e=new Date,f=e.getFullYear(),g=e.getMonth(),e=e.getDate();if(c=elm(c))c.value=formatDate(new Date(f,g,e+b),"yyyy-MM-dd");if(d=elm(d))d.value=formatDate(new Date(f,g,e+a),"yyyy-MM-dd")}
function xDatePicker(b){WdatePicker({skin:"msp",dateFmt:b==1?"yyyy-MM-dd":"yyyy-MM-dd HH:mm:ss"})}
function xDatePicker2(b){WdatePicker({skin:"msp",dateFmt:b==1?"yyyy-MM":"yyyy-MM-dd HH:mm:ss"})}
function ajax(b,c,a,d){if(!$p.loading){loading(!0);var e=null;if(window.XMLHttpRequest)e=new XMLHttpRequest;else try{e=new ActiveXObject("Microsoft.XMLHTTP")}catch(f){e=new ActiveXObject("Msxml2.XMLHTTP")}e.open("post",b,d!=null&&!d?!1:!0);e.setRequestHeader("Content-Type","application/x-www-form-urlencoded");b="";if(c!=null)for(var g in c)c[g]!=null&&(b+=g+"="+encodeURIComponent(c[g])+"&");e.send(b);d!=null&&!d?a(e.responseText):e.onreadystatechange=function(){e.readyState==4&&(loading(!1),e.status==
200?e.responseText==""?alert("\u6ca1\u6709\u6743\u9650\u6216\u7cfb\u7edf\u8d85\u65f6"):a(e.responseText):e.status==0?alert("\u957f\u65f6\u95f4\u672a\u64cd\u4f5c\uff0c\u8bf7\u5237\u65b0\u9875\u9762\u540e\u91cd\u65b0\u64cd\u4f5c"):alert("\u51fa\u9519\u4e86,\u8bf7\u8054\u7cfb\u5ba2\u670d("+e.status+")"))}}}
function hdAjax(b,c,a){var d=null;if(window.XMLHttpRequest)d=new XMLHttpRequest;else try{d=new ActiveXObject("Microsoft.XMLHTTP")}catch(e){d=new ActiveXObject("Msxml2.XMLHTTP")}d.open("post",b,!0);d.setRequestHeader("Content-Type","application/x-www-form-urlencoded");b="";if(c!=null)for(var f in c)c[f]!=null&&(b+=f+"="+encodeURIComponent(c[f])+"&");d.send(b);d.onreadystatechange=function(){d.readyState==4&&d.status==200&&d.responseText!=""&&a(d.responseText)}}
function myAjaxQuery(b,c,a){if(!checkBeforeQuery||checkBeforeQuery()){var d=(new Date).getTime(),a=forParams(a);a.pageNo=!b?1:elm("pageNo").value;a.pageSize=elm("pageSize").value;ajax(c,a,function(a){elm("listDiv").innerHTML=a;pagingFeedback();dataListTrMouseClass();if(a=elm("ajaxQueryCostTime"))a.innerHTML="\u8017\u65f6\uff1a"+((new Date).getTime()-d)/1E3+"\u79d2"})}}
function ajaxQuery(b,c,a){if(!checkBeforeQuery||checkBeforeQuery()){var d=(new Date).getTime();a.pageNo=!b?1:elm("pageNo").value;a.pageSize=elm("pageSize").value;ajax(c,a,function(a){elm("listDiv").innerHTML=a;pagingFeedback();dataListTrMouseClass();if(a=elm("ajaxQueryCostTime"))a.innerHTML="\u8017\u65f6\uff1a"+((new Date).getTime()-d)/1E3+"\u79d2"})}}
function myAsyncDownload(b,c){if(!checkBeforeQuery||checkBeforeQuery()){var a=forParams(c);ajax(b,a,function(a){twPage("auto","auto",400,100,"\u4e0b\u8f7d\u4fe1\u606f","html",a)})}}function asyncDownload(b,c){(!checkBeforeQuery||checkBeforeQuery())&&ajax(b,c,function(a){twPage("auto","auto",400,100,"\u4e0b\u8f7d\u4fe1\u606f","html",a)})}function checkBeforeQuery(){return!0}
function cleanAllCond(b,c){var a={};if(c!=null)for(var d=0;d<c.length;d++)a[c[d]]=c[d];for(d=0;d<b.length;d++)if(a[b[d]]==null){var e=elm(b[d]);if(e!=null&&e.tagName&&e.tagName=="INPUT"&&(e.type=="text"||e.type=="hidden"))e.value="",b[d].indexOf("msh$")==0&&cleanMselect(b[d].substring(4))}}
function pagingAjax(b,c,a,d){var e=parseInt(b,10),e=""+e=="NaN"?1:e,e=e!=b?1:e;if(d||!(e==c||e<1||e>a))b=elm("pageSize"),c=parseInt(b.value,10),c=""+c=="NaN"?10:c,b.value=c!=b.value||c<1?10:c,b.value=c>100?100:c,elm("pageNo").value=e,myQuery(1)}
function pagingReposition(){var b=elm("pagingDiv");if(b!=null){var c=document.documentElement.scrollTop||document.body.scrollTop;c>$p.pagingDivTop?(b.style.position="absolute",b.style.top=c+"px",elm("pagingDivPuppet").style.display=""):(b.style.position="",elm("pagingDivPuppet").style.display="none")}}function pagingFeedback(){var b=elm("pagingDivDone");if(b)elm("pagingDiv").innerHTML=b.innerHTML,b.parentNode.removeChild(b)}
function dataListTrMouseClass(){var b=elm("listTb");if(b!=null)for(var b=b.childNodes,c=0;c<b.length;c++)if(b[c].tagName&&""+b[c].tagName=="TBODY")for(var a=b[c].childNodes,d=0,e=0;e<a.length;e++)if(a[e].tagName&&a[e].tagName=="TR"){if(d>0)a[e].onmouseover=new Function("this.className='mouseover';"),a[e].onmouseout=new Function("this.className='';");d+=1}}
function getElementOffset(b){var c=b.offsetLeft,a=b.offsetTop;b.offsetParent&&(b=getElementOffset(b.offsetParent),c+=b.left,a+=b.top);return{left:c,top:a}}function getElementWidthHeight(b){return{width:b.scrollWidth,height:b.scrollHeight}}function getWindowWidthHeight(){return{width:document.body.offsetWidth,height:document.body.offsetHeight}}
function getBodyScrollWidthHeight(){return document.documentElement.scrollTop?{left:document.documentElement.scrollLeft,top:document.documentElement.scrollTop}:{left:document.body.scrollLeft,top:document.body.scrollTop}}
function twPage(b,c,a,d,e,f,g,h){if($p.twPage==null)$p.twPage=document.createElement("DIV"),$p.twPage.className="twPage",document.body.appendChild($p.twPage),$p.twPage.innerHTML='<div class="twHead"><div class="twTitle" id="twTitle"></div><div class="twClose" onclick="closeTwPage();"></div></div><div class="twContent" id="twContent"></div>';if("auto"!=b)$p.twPage.style.left=b+"px";if("auto"!=c)$p.twPage.style.top=c+"px";$p.twPage.style.width="auto"==a?a:a+"px";$p.twPage.style.height="auto"==d?d:d+
"px";if("auto"==b||"auto"==c){var d=getWindowWidthHeight(),l=getElementWidthHeight($p.twPage);if("auto"==b)$p.twPage.style.left=(d.width-("auto"==a?l.width:a))/2+"px";if("auto"==c)$p.twPage.style.top=(d.height-l.height)/2+"px"}"html"==f?(elm("twContent").innerHTML=g,$p.twPage.style.display=""):"url"==f&&ajax(g,h,function(a){elm("twContent").innerHTML=a;$p.twPage.style.display=""});elm("twTitle").innerHTML=e}function closeTwPage(){$p.twPage.style.display="none"}
function showTipPic(b,c,a,d,e,f){var g=endsWith(c,["jpg","jpeg","gif","bmp","png"]);if($p.tipPic==null){var h=document.createElement("div");h.className="tipPic";h.style.width=a+"px";h.style.height=d+"px";h.style.lineHeight=d+"px";$p.tipPic=h;document.body.appendChild(h)}$p.tipPic.innerHTML=g?'<img src="'+c+'" style="width:100%;height:100%;" />':"\u975e\u56fe\u7247\u683c\u5f0f\uff0c\u8bf7\u4fdd\u5b58\u5230\u672c\u5730\u540e\u67e5\u770b";$p.tipPic.style.display="";b=getElementOffset(b);if(e==null)e=
getWindowWidthHeight(),$p.tipPic.style.left=(e.width-a)/2+"px",$p.tipPic.style.top=b.top+20+"px";else if(e=="near")$p.tipPic.style.left=b.left-f+"px",$p.tipPic.style.top=b.top+20+"px"}function closeTipPic(){$p.tipPic.style.display="none"}function myMenu(){return!0}function myKeyDown(b){if(b.keyCode==17)$p.ctrlFlag=!0}function myKeyUp(b){if(b.keyCode==17)$p.ctrlFlag=!1}
window.attachEvent?(document.attachEvent("onkeydown",myKeyDown),document.attachEvent("onkeyup",myKeyUp)):(document.addEventListener("keydown",myKeyDown,!1),document.addEventListener("keyup",myKeyUp,!1));var $ms={allOptTxt:"--\u5168\u90e8--",notInitMshIds:[],isInitMshAllOptTxt:!0,lastMselectId:null,mselectId:null,clkRcdElm:{}};function mselect(b,c,a,d,e,f,g,h,l,n,q){$p.lastMselectId=$p.mselectId;$p.mselectId=c+"_mselect";makeMselect(b,c,a,d,e,f,g,h,l,n,q)}
function mselectDct(b,c,a,d,e,f,g,h,l,n){$p.lastMselectId=$p.mselectId;$p.mselectId=c+"_mselect";makeMselect(b,c,contextPath+"/common/dictionary/forSelect.do?label="+a,d,e,f,g,h,l,n)}
function makeMselect(b,c,a,d,e,f,g,h,l,n,q){var i=elm(c+"_mselect");if(!(i==null&&a==null)){var p=d?!0:!1,s=g==null?1:g,t=h?h:1,o=n?!0:!1;if(i==null)if(i=document.createElement("DIV"),i.onclick=new Function("$ms.clkRcdElm[this.id.substring( 0, this.id.length - 8 )] = 1;"),i.id=c+"_mselect",i.className="mselect",i.innerHTML="\u8f7d\u5165\u6570\u636e...",i.style.width=e+"px",i.style.height=f=="auto"?"auto":f+"px",i.style.overflow="auto",i.callBack=l,b.parentNode.appendChild(i),typeof a=="string")ajax(a,
{},function(a){a=eval(a);i.innerHTML=makeOptions(c,a,p,e,s,t,o,q)});else if(typeof a=="object")i.innerHTML=makeOptions(c,a,p,e,s,t,o,q);i.style.display="";setPositionMselect()}}
function makeOptions(b,c,a,d,e,f,g,h){g=g?"":'<div class="row"><input type="checkbox" '+(!a?'style="display:none;"':"")+' disabled/><a href="#" style="width:'+(d-(!a?20:40))+'px;" onclick="chooseMsValue(\''+b+"','');return false;\">&nbsp;"+$ms.allOptTxt+"</a></div>";h=h||"optionsMouseEvent";mover=h+"(event,this,'over');return false;";mout=h+"(event,this,'out');return false;";for(h=0;h<c.length;h++){var l=c[h].key?c[h].key:c[h].k,n=c[h].value?c[h].value:c[h].v,q=c[h].s,i="";q&&(i='<input type="text" style="display:none;" id="mscbtext$'+
b+l+'" value="'+q+'" />');g=g+'<div class="ellipsis row" '+(h!=c.length-1?"":'style="border-bottom:0px;"')+' ><input type="checkbox" '+(!a?'style="display:none;"':"")+' name="mscb$'+b+'" value="'+l+'" onclick="compMsValue( \''+b+'\' );" /><input type="checkbox" style="display:none;" name="mscbt$'+b+'" value="'+(f==1?n:l+"-"+n)+'" />'+i+'<a style="width:'+(d-(!a?20:40))+'px;" href="#" onclick="chooseMsValue(\''+b+"','"+l+'\');return false;" onmouseover="'+mover+'" onmouseout="'+mout+'" >&nbsp;'+(e==
0?l:e==1?n:l+"-"+n)+"</a></div>"}return g}function optionsMouseEvent(b,c,a){c.className=a=="over"?"mselectOver":"mselectOut"}function removeMselect(b){var c=elm(b+"_mselect");c!=null&&c.parentNode.removeChild(c);elm(b).value="";elm("msh$"+b).value=$ms.allOptTxt}
function blurMselect(b){var c=b.srcElement||b.target;window.setTimeout(function(){if(c.id&&c.id.length>3&&c.id.substring(0,4)=="msh$"){if($p.lastMselectId!=$p.mselectId&&$p.lastMselectId!=null){var a=elm($p.lastMselectId);if(a!=null)a.style.display="none"}}else if((!c.name||!(c.name.length>4&&c.name.substring(0,5)=="mscb$"))&&$p.mselectId!=null)if(a=elm($p.mselectId),a!=null)a.style.display="none"},140)}
function chooseMsValue(b,c){var a=elms("mscb$"+b);if(a!=null&&a.length>0)if(c=="")for(var d=0;d<a.length;d++)a[d].checked=!1;else for(d=0;d<a.length;d++)a[d].checked=a[d].value==c?!0:!1;compMsValue($p.mselectId.substring(0,$p.mselectId.length-8))}
function compMsValue(b){var c=elm("msh$"+b);if(c.tagName=="INPUT"&&$ms.clkRcdElm[b]==0)elm(b).value=c.value;else{var a=elms("mscb$"+b),d=elms("mscbt$"+b),e="",f="";if(a!=null)for(var g=0;g<a.length;g++)a[g].checked&&(e+=a[g].value+",",f+=d[g].value+",");a=e.length>0?e.substring(0,e.length-1):e;elm(b).value=a;c.value=f.length>0?f.substring(0,f.length-1):f;c.value=c.value==""?$ms.allOptTxt:c.value;f=elm(b+"_mselect").callBack;f!=null&&f(a,c.value,b)}}
function matchCheckedMselect(b,c){for(var a=c.split(","),d={},e=0;e<a.length;e++){var f=trim(a[e]);f!=""&&(d[f]=f)}a=elms(b);for(e=0;e<a.length;e++)a[e].checked=d[a[e].value]!=null?!0:!1}function setPositionMselect(){if($p.mselectId){var b=elm($p.mselectId);if(b){var c=getElementOffset(elm("msh$"+$p.mselectId.substring(0,$p.mselectId.length-8)));b.style.left=c.left+"px";b.style.top=c.top+23+"px"}}}
function cleanMselect(b){for(var c=elms("mscb$"+b),a=0;a<c.length;a++)if(c[a].checked)c[a].checked=!1;try{elm("msh$"+b).value=$ms.allOptTxt}catch(d){alert(d.message)}}function setMselectValue(b,c,a,d){for(var e=0;e<c.length;e++)if(a==c[e].k||a==c[e].key)elm(b).value=a,elm("msh$"+b).value=d==1?c[e].v:a+"-"+c[e].v}var $initMselectFlag=!0;
function initMselectLabelValue(){if($ms.isInitMshAllOptTxt)for(var b=document.getElementsByTagName("INPUT"),c=0;c<b.length;c++){var a=b[c];if(a.type=="text"&&a.id&&a.id.length>3&&a.id.substring(0,4)=="msh$"){for(var d=!0,e=0;e<$ms.notInitMshIds.length;e++)if(a.id==$ms.notInitMshIds[e]){d=!1;break}if($initMselectFlag&&d)a.value=$ms.allOptTxt}}}
(function(){window.attachEvent?(window.attachEvent("onresize",setPositionMselect),document.attachEvent("onclick",blurMselect),window.attachEvent("onload",initMselectLabelValue)):(window.addEventListener("resize",setPositionMselect,!1),document.addEventListener("click",blurMselect,!1),window.addEventListener("load",initMselectLabelValue))})();
function labelAndMenuChoose(b,c){var a="";if(b!=null&&b!="")a=b;else{var d=c.substring(0,c.indexOf("/"));d!="common"&&(a=d)}labelChoose(a,c);menuChoose(a,c)}
function labelChoose(b,c){if(c){for(var a=elm("labelZone").childNodes,d=null,e=!1,f=0;f<a.length;f++)if("DIV"==a[f].tagName&&"splitor"!=a[f].className){d==null&&(d=a[f]);if(b==null||b=="")b=a[f].id.substring(6),elm("label$").value=b;a[f].id=="label$"+b?(a[f].className="labelOn",e=!0):a[f].className="label"}if(!e&&d!=null)d.className="labelOn",b=d.id.substring(6),loadIndexPage(b);a=elm("menuZone").childNodes;for(f=0;f<a.length;f++)if("SPAN"==a[f].tagName)a[f].style.display=a[f].id=="menu$common"||
a[f].id=="menu$"+b?"":"none";if(f=elm("menu$common")){a=f.childNodes;for(f=0;f<a.length;f++)if("A"==a[f].tagName)a[f].href=a[f].href.substring(0,a[f].href.indexOf(".do"))+".do?label$=common"}}else toIndexPage(b)}function menuChoose(b,c){if(b)for(var a=elm("menu$"+b).childNodes,d=0;d<a.length;d++)if("A"==a[d].tagName&&(""+a[d].href).indexOf(c+".do")!=-1)a[d].className="menuOn"}
function initPaging(){window.attachEvent?(window.attachEvent("onscroll",pagingReposition),window.attachEvent("onresize",pagingReposition)):(window.addEventListener("scroll",pagingReposition),window.addEventListener("resize",pagingReposition));$p.pagingDivTop=getElementOffset(elm("pagingDiv")).top}
var snda_os_webrefer_ufg={gm:124002,triggers:{floatwin:["010101","010102"],extend:[{triggerid:"OnlineFAQLink",source:"010103"}]},t:"\u76db\u4ed8\u901a\u7ebf\u4e0b\u6536\u5355\u4f5c\u4e1a\u5e73\u53f0(MSP)\u76f8\u5173\u95ee\u9898",adjustright:0,adjusttop:250,switchwaiting:6048E5,hidewidgetwindow:!1,pushwords:"\u60a8\u5df2\u7ecf\u5728\u9875\u9762\u505c\u7559\u5f88\u4e45\u4e86\uff0c\u8bf7\u95ee\u6709\u4ec0\u4e48\u9700\u8981\u5e2e\u52a9\u7684\u5417\uff1f",inputnotice:"\u8bf7\u8f93\u5165\u60a8\u7684\u95ee\u9898\u6216\u76f4\u63a5\u70b9\u51fb\u53d1\u9001",
imgpath:contextPath+"/htdocs/msp/img/OnlineFAQLink/"};
(function(b,c){function a(){if(q==1&&i!=c&&i.style.display!="none")i.style.position="absolute",i.style.top=(parseInt(l())-s.h)/2+parseInt(h())+k.getAdjustTop()+"px",i.style.right=5+k.getAdjustRight()+"px",i.style.display="block";if(q==2&&p!=c&&p.style.display!="none")p.style.position="absolute",p.style.top=(parseInt(l())-t.h)/2+parseInt(h())+k.getAdjustTop()+"px",p.style.right=5+k.getAdjustRight()+"px",p.style.display="block"}function d(a){return typeof a=="object"&&a!=null&&typeof a.outerHTML=="string"?
a:typeof a=="function"?a():/^([a-z]|[A-Z]|\_)\w{0,}$/.test(a)?document.getElementById(a):null}function e(a){return typeof a!="string"?a:a.replace(/(^\s*)|(\s*$)/g,"")}function f(a,b,c){typeof a!="object"||typeof b!="string"||typeof c!="function"&&typeof c!="object"||(a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener&&a.addEventListener(b,c,!1))}function g(a){var c="",d="",f="";a==1?d=o.t:(d=e(r.value),d=d.length==0||d==k.inputnotice?o.t:o.t+"( "+d.substring(0,200)+" )");var f=a==1?o.triggers.floatwin[0]:
o.triggers.floatwin[1],h;for(h in o)c+=h=="t"?"&t="+escape(d):h=="triggers"?"&source="+f:"&"+e(h.toString())+"="+escape(o[h].toString());c.length>0&&(c=c.substring(1));b.snda_os_widget.extend.linkHandler(c)}function h(){var a=0;if(document.documentElement&&document.documentElement.scrollTop)a=document.documentElement.scrollTop;else if(document.body)a=document.body.scrollTop;return a}function l(){return document.body.clientHeight&&document.documentElement.clientHeight?document.body.clientHeight<document.documentElement.clientHeight?
document.body.clientHeight:document.documentElement.clientHeight:document.body.clientHeight>document.documentElement.clientHeight?document.body.clientHeight:document.documentElement.clientHeight}function n(){var j=b.snda_os_webrefer_ufg;if(j==c||j==null||typeof j!="object")alert("\u60a8\u5df2\u7ecf\u5f15\u5165\u3010\u76db\u5927\u5728\u7ebf\u5ba2\u670d\u3011\u7684\u811a\u672c\u63a5\u53e3\uff0c\u4f46\u5c1a\u672a\u5bf9\u63a5\u5165\u53c2\u6570\u8fdb\u884c\u914d\u7f6e\u3002\n\n\u63d0\u793a\uff1a\n-------------------\n\u201csnda_os_widget.js\u201d\u6216\u201csnda_os_widget.min.js\u201d\u5e93\u6587\u4ef6\u7684\u5f15\u5165\u9700\u8981\u4f4d\u4e8e\u201cvar snda_os_webrefer_ufg = ...\u201d\u5b9a\u4e49\u4e4b\u540e\u3002");
else if(/^\d{1,9}$/.test(j.gm))if(!j.triggers||typeof j.triggers!="object"||!j.triggers.floatwin instanceof Array||j.triggers.floatwin.length!=2||!/^\d{6}$/.test(j.triggers.floatwin[0])||!/^\d{6}$/.test(j.triggers.floatwin[1]))alert("\u60a8\u5df2\u7ecf\u5f15\u5165\u3010\u76db\u5927\u5728\u7ebf\u5ba2\u670d\u3011\u7684\u811a\u672c\u63a5\u53e3\uff0c\u4f46\u5c1a\u672a\u6709\u6548\u914d\u7f6e\u5fc5\u9700\u7684\u63a5\u5165\u53c2\u6570\uff08\u6e20\u9053\u4ee3\u7801\u4e3a6\u4f4d\u6570\u5b57\uff09");else{var n=
typeof j.pushwords=="string"?j.pushwords:"\u60a8\u5df2\u7ecf\u5728\u9875\u9762\u505c\u7559\u5f88\u4e45\u4e86\uff0c\u8bf7\u95ee\u6709\u4ec0\u4e48\u9700\u8981\u5e2e\u52a9\u7684\u5417\uff1f",m=typeof j.imgpath=="string"?j.imgpath:"images_7k_2lc/";m.charAt(m.length-1)!="/"&&(m+="/");var A='<div class="mod_custom_service_small" id="k9_x_OS_all"><p class="os_p_close"><a href="#" id="k9_x_step1CloseBtn" title="\u5173\u95ed" ><img src="'+m+'btn_close_small.gif" alt="" /></a></p></div>',n='<div class="mod_custom_service" id="k9_x_osAll"><p class="os_p_textarea"><textarea id="k9_x_txtarea_qword" cols="20" rows="25"></textarea></p><p class="os_p_btn"><button id="k9_x_btn_connectoos" type="button" ><img src="'+
m+'close_send_ez.png" alt="" /></button></p><p class="os_p_close" id="k9_x_step2CloseBtn" title="\u5173\u95ed"><a href="#" ><img src="'+m+'btn_close.gif" alt="" /></a></p><p class="os_words_ez" id="k9_x_pushwords">'+n+"</p></div>";o.gm=j.gm;o.triggers=j.triggers;if(j.ar)o.ar=j.ar.toString();if(j.sv)o.sv=j.sv.toString();if(j.t)o.t=j.t.toString();k.connectfrom=0;k.popswitch=!0;k.faceindex=0;k.inputnotice=typeof j.inputnotice=="string"?j.inputnotice:"\u8bf7\u8f93\u5165\u60a8\u7684\u95ee\u9898\u6216\u76f4\u63a5\u70b9\u51fb\u53d1\u9001";
k.switchwaiting=typeof j.switchwaiting=="number"?Math.abs(j.switchwaiting):432E3;k.getAdjustTop=function(){return typeof j.adjusttop=="function"?j.adjusttop():!isNaN(j.adjusttop)?j.adjusttop:0};k.getAdjustRight=function(){return typeof j.adjustright=="function"?j.adjustright():!isNaN(j.adjustright)?j.adjustright:0};if(typeof b.beforeLoadingOsWebReferInterface=="function")try{b.beforeLoadingOsWebReferInterface()}catch(B){}b.snda_os_widget={extend:{linkHandler:function(a){typeof b.snda_os_webrefer_oswin==
"object"&&!b.snda_os_webrefer_oswin.closed?alert("\u60a8\u5df2\u7ecf\u6253\u5f00\u4e86\u4e00\u4e2a\u3010\u76db\u5927\u5728\u7ebf\u5ba2\u670d\u3011\u7a97\u53e3\uff0c\u8bf7\u5173\u95ed\u65e7\u7a97\u53e3\u540e\u518d\u6253\u5f00\u3002"):(b.snda_os_webrefer_url="http://os.sdo.com/default.aspx?"+a,b.snda_os_webrefer_oswin=b.open(b.snda_os_webrefer_url,"","toolbar=no,location=no,left="+(b.screen.width-640)/2+",top="+(b.screen.height-480)/2+",directories=no,scrollbars=no,menubar=no,width=465,height=455,resizable=no,status=no"))}}};
if(j.hidewidgetwindow!=!0){var m=document.createElement("link"),w=document.createElement("div"),x=document.createElement("div"),u=document.createDocumentFragment();w.style.display="none";x.style.display="none";m.type="text/css";m.rel="Stylesheet";w.innerHTML=A;x.innerHTML=n;u.id="_t5Kze73_RW_6__6ggtLim__82";u.appendChild(w);u.appendChild(x);document.body.appendChild(m);document.body.appendChild(u);i=d("k9_x_OS_all");p=d("k9_x_osAll");var v={right:5+k.getAdjustRight()+"px"};q=1;i.style.top=(parseInt(l())-
s.h)/2+parseInt(h())+"px";i.style.right=v.right;i.style.display="block";setTimeout(function(){if(!(k.connectfrom==1||k.popswitch==!1))i.style.display="none",q=2,p.style.top=(parseInt(l())-t.h)/2+parseInt(h())+"px",p.style.right=v.right,p.style.display="block",a()},k.switchwaiting);a();i.onclick=function(){g(1);k.connectfrom=1;return!1};d("k9_x_step1CloseBtn").onclick=function(a){i.style.display="none";k.popswitch=!1;(a?a:b.event).cancelBubble=!0};r=d("k9_x_txtarea_qword");r.value=k.inputnotice;r.style.color=
"#4cc0ef";f(r,"keydown",function(a){if(a.keyCode==13)return a.shiftKey?!0:(g(2),k.connectfrom=2,q=1,p.style.display="none",i.style.top=(parseInt(l())-s.h)/2+parseInt(h())+"px",i.style.right=v.right,i.style.display="block",!1)});f(r,"focus",function(){var a=e(r.value);r.style.color="#4cc0ef";if(a==k.inputnotice)r.value=""});f(r,"blur",function(){var a=e(r.value);r.style.color="#4cc0ef";if(a.length==0)r.value=k.inputnotice});d("k9_x_btn_connectoos").onclick=function(){g(2);k.connectfrom=2;q=1;p.style.display=
"none";i.style.top=(parseInt(l())-s.h)/2+parseInt(h())+"px";i.style.right=v.right;i.style.display="block";return!1};d("k9_x_step2CloseBtn").onclick=function(){p.style.display="none";i.style.right=5+k.getAdjustRight()+"px";i.style.display="block";a();q=1;return!1};f(b,"resize",function(){a()});f(b,"scroll",function(){a()});a()}if(j.triggers.extend instanceof Array)for(var y in j.triggers.extend){var m=j.triggers.extend[y].triggerid,z=j.triggers.extend[y].source;if((typeof m=="string"&&m.length>0||
typeof m=="function"||typeof m=="object"&&m!=null&&typeof m.outerHTML=="string")&&/^\d{6}$/.test(z))if(m=d(m),typeof m!=null)try{f(m,"click",new function(){var a=z;return function(){var c="",d;for(d in o)c+=d.toString()=="triggers"?"&source="+a:"&"+e(d.toString())+"="+escape(o[d].toString());c.length>0&&(c=c.substring(1));k.popswitch=!1;b.snda_os_widget.extend.linkHandler(c);return!1}})}catch(C){}}if(typeof b.afterLoadingOsWebReferInterface=="function")try{b.afterLoadingOsWebReferInterface()}catch(D){}}else alert("\u60a8\u5df2\u7ecf\u5f15\u5165\u3010\u76db\u5927\u5728\u7ebf\u5ba2\u670d\u3011\u7684\u811a\u672c\u63a5\u53e3\uff0c\u4f46\u5c1a\u672a\u6709\u6548\u914d\u7f6e\u5fc5\u9700\u7684\u63a5\u5165\u53c2\u6570\uff08\u6e38\u620f\u4ee3\u7801\u4e3a\u6570\u5b57\uff09")}
var q=0,i,p,s={w:82,h:103},t={w:180,h:298},o={},k={},r;document.readyState=="complete"?n():f(b,"load",n)})(window,void 0);function showIndexPage(){var b=window.$mnMain,c=b.vars.currentLabel;if(b.isNeedToLoadIndex(c)){var a=document.getElementById("topFm");elm("label$").value=c;a.action=contextPath+"/common/main/index.do";setTimeout(function(){a.submit()},0)}}
function loadIndexPage(b){if(!(b!="posPromoter"&&b!="mposPromoter"&&b!="posMerchant")){elm("label").value=b;var b=contextPath+"/common/main/loadMainPage.do",c=elm("tFm");c.action=b;c.submit()}}function invokeClick(b){if(b.click)b.click();else if(b.fireEvent)b.fireEvent("onclick");else if(document.createEvent){var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);b.dispatchEvent(c)}}
function ctrlSuite(b,c,a){var d=elm(b);$p.ctrlAssVar.showElm[b]=d;c?($p.ctrlAssVar.showFlg[b]=!0,c=elm(a),b=getElementOffset(c),c=getElementWidthHeight(c),d.style.left=b.left+c.width-parseInt(d.style.width)+"px",d.style.top=b.top+c.height+"px",d.style.display=""):($p.ctrlAssVar.showFlg[b]=!1,window.setTimeout("hideSuite( '"+b+"' )",60))}function hideSuite(b){if(!$p.ctrlAssVar.showFlg[b])$p.ctrlAssVar.showElm[b].style.display="none"}
function MyMenu(b,c){this.mouseoutSeq=0;this.mouseoutMap={};this.menuUl=document.getElementById(b);this.vars={pageNo:1,pageSize:2,pageLimit:0,hLightPos:0,menuCellWidth:120,mtFlagCnt:0,currentLabel:null,fas:[]};this.chsMcType=function(a){this.vars.currentLabel?this.isNeedToLoadIndex(a)?this.toIndexPage(a):(this.vars.currentLabel=a,this.toShowMeType(a),this.showMyLabel(a)):(this.vars.currentLabel=a,this.toShowMeType(a),this.showMyLabel(a))};this.isNeedToLoadIndex=function(a){if(window.location.href.indexOf("index.do")==
-1)return!0;else if(a!=this.vars.currentLabel)return!0;return!1};this.init=function(a){if(this.isNeedToFirstLabel(a)){if(a=elm("roMchTypeE0").getElementsByTagName("A"),a.length>0||a.onclick)a[0].onclick()}else this.toShowMeType(this.vars.currentLabel),this.showMyLabel(this.vars.currentLabel)};this.isNeedToFirstLabel=function(a){if(a==null||a==""||a=="common")a=this.vars.currentLabel;return a==null||a==""||a=="common"?!0:!1};this.showMyLabel=function(a){for(var b=this.menuUl.getElementsByTagName("li"),
e=0;e<b.length;e++)if(b[e].className=="menu$"+a||"menu$common"==b[e].className){b[e].style.display="";this.vars.fas[this.vars.mtFlagCnt]=b[e];this.vars.mtFlagCnt++;for(var f=b[e].getElementsByTagName("A"),g=0;g<f.length;g++)if(f[g].name=="menu$common")f[g].href=f[g].href.substring(0,f[g].href.indexOf(".do"))+".do?mType$="+a;b[e].onmouseover=function(){for(var a=this.childNodes,b=0;b<a.length;b++)if(a[b]&&a[b].tagName=="UL"){a[b].myDisp="1";a[b].className="mnSub";if(window[c].getMenuLevel(a[b])>=3)if(document.all){var d=
a[b].parentNode;a[b].style.position="absolute";a[b].style.left=d.clientWidth+d.offsetLeft+"px";a[b].style.top=d.offsetTop+"px"}else a[b].style.position="relative",a[b].style.left="160px",a[b].style.top="-24px";break}};b[e].onmouseout=function(){for(var a=this.childNodes,b=0;b<a.length;b++)if(a[b]&&a[b].tagName=="UL"){a[b].myDisp="0";if(document.all){var d=window[c];d.mouseoutSeq+=1;d.mouseoutMap[""+d.mouseoutSeq]=a[b];window.setTimeout(c+".hideSub('"+d.mouseoutSeq+"')",50)}else a[b].className="mnSub mnSubHidden";
break}}}this.menuUl.style.display=""};this.hideSub=function(a){if(this.mouseoutMap[a].myDisp=="0")this.mouseoutMap[a].className="mnSub mnSubHidden",this.mouseoutMap[a]=null};this.getMenuLevel=function(a){for(var c=0;a;){if(a.tagName=="UL"&&(c+=1,a.id==b))return c;a=a.parentNode}};this.highLightMenu=function(a){for(var b=window.location.href,b=b.substring(b.indexOf(contextPath)+contextPath.length+1,b.indexOf(".do")),a=b.indexOf(a)==-1?b+".do?mType$="+a:b+".do",b=this.menuUl.getElementsByTagName("A"),
c=0;c<b.length;c++)if(endsWith(b[c].href,["/"+a])){b[c].className+=" choosed";for(a=b[c];a;){a.tagName=="LI"&&(a.className+=" choosed");if(a==this.menuUl)break;a=a.parentNode}break}};this.setCurrentLabel=function(a,b){a||b&&b!="common"&&(a=b);this.vars.currentLabel=a};this.toIndexPage=function(a){var b=elm("topFm");elm("label$").value=a;b.action=contextPath+"/common/main/index.do";b.submit()};this.toShowMeType=function(a){if(a!=""&&a!="common")a={posPromoter:"POS\u4ee3\u7406\u5546",posMerchant:"POS\u5546\u6237",
mposPromoter:"MPOS\u4ee3\u7406\u5546",mposSDK:"MPOS-SDK\u4ee3\u7406\u5546",factory:"\u673a\u5177\u5382\u5546"}[a],elm("roMchTypeE1Label").innerHTML=a}};
